services:
  ib-gateway:
    image: johntfoster/ib-tws:latest
    environment:
      TWSUSERID: $TWSUSERID
      TWSPASSWORD: $TWSPASSWORD
      TRADING_MODE: paper
    ports:
      - 5900:5900
      - 7497:7497
    restart: always
